module.exports = {
  TICK_INTERVAL: 10,
  ALPHA: 0.01,

  EXPERIENCE_ON_FAILURE: -1,
  EXPERIENCE_ON_SUCCESS: 1,


  PIPE_WIDTH: 138,
  GAP_HEIGHT: 250,
  GAME_HEIGHT: 896,
  X_OFFSET_WHEN_NO_PIPES: 100
};
